#! /usr/bin/env bash
# Modify next line and set destination drive to match mbed device
export LPC_DEPLOY='cp PROJECT.bin /Volumes/MBED/'

SCRIPT_PATH=$0
SCRIPT_PATH=${SCRIPT_PATH%/*}
cd $SCRIPT_PATH
SCRIPT_PATH=$PWD
export PATH=$SCRIPT_PATH/arm-2011.03/bin:$PATH
exec bash
