extern const char http_get[5];
extern const char http_post[6];
extern const char http_options[9];
extern const char http_10[9];
extern const char http_11[9];
extern const char http_content_length[17];
extern const char http_cache_control[16];
extern const char http_no_cache[9];
extern const char http_index_html[12];
extern const char http_404_html[10];
extern const char http_header_preflight[141];
extern const char http_header_200[18];
extern const char http_header_304[116];
extern const char http_header_404[25];
extern const char http_header_503[22];
extern const char http_header_all[69];
extern const char http_content_type_plain[29];
extern const char http_content_type_html[28];
extern const char http_content_type_css [27];
extern const char http_content_type_text[28];
extern const char http_content_type_png [28];
extern const char http_content_type_gif [28];
extern const char http_content_type_jpg [29];
extern const char http_html[6];
extern const char http_css[5];
extern const char http_png[5];
extern const char http_gif[5];
extern const char http_jpg[5];
extern const char http_txt[5];
