

EVENT(ON_MAIN_LOOP, on_main_loop)
EVENT(ON_CONSOLE_LINE_RECEIVED, on_console_line_received)
EVENT(ON_GCODE_RECEIVED, on_gcode_received)
EVENT(ON_GCODE_EXECUTE, on_gcode_execute)
EVENT(ON_SPEED_CHANGE, on_speed_change)
EVENT(ON_BLOCK_BEGIN, on_block_begin)
EVENT(ON_BLOCK_END, on_block_end)
EVENT(ON_CONFIG_RELOAD, on_config_reload)
EVENT(ON_PLAY, on_play)
EVENT(ON_PAUSE, on_pause)
EVENT(ON_IDLE, on_idle)
EVENT(ON_CONFIG_VALUE, on_config_value)
EVENT(ON_CONFIG_COMPLETE, on_config_complete)
EVENT(ON_SECOND_TICK, on_second_tick)
EVENT(ON_GET_PUBLIC_DATA, on_get_public_data)
EVENT(ON_SET_PUBLIC_DATA, on_set_public_data)
