#pragma once

#include <stdint.h>

/**
 * Icons
 * 
 * Made with Marlin Bitmap Converter
 * http://marlinfw.org/tools/u8glib/converter.html
 *
 * This bitmap from the file 'firmware-logo.png'
 */

#define icon_width  8
#define icon_height 8

static const uint8_t hotend_icon[] = {
  0x7C, // .#####..
  0x10, // ...#....
  0x7C, // .#####..
  0x10, // ...#....
  0x38, // ..###...
  0x38, // ..###...
  0x10, // ...#....
  0x00  // ........
};

static const uint8_t bed_icon[] = {
  0x24, // ..#..#..
  0x48, // .#..#...
  0x24, // ..#..#..
  0x48, // .#..#...
  0x24, // ..#..#..
  0x00, // ........
  0xFE, // #######.
  0x00  // ........
};

static const uint8_t fan_icon[] = {
  0x00, // ........
  0x4C, // .#..##..
  0x68, // .##.#...
  0x10, // ...#....
  0x2C, // ..#.##..
  0x64, // .##..#..
  0x00, // ........
  0x00  // ........
};

static const uint8_t speed_icon[] = {
  0x90, // #..#....
  0x48, // .#..#...
  0x24, // ..#..#..
  0x12, // ...#..#.
  0x24, // ..#..#..
  0x48, // .#..#...
  0x90, // #..#....
  0x00  // ........
};

static const uint8_t time_icon[] = {
  0x38, // ..###...
  0x44, // .#...#..
  0x92, // #..#..#.
  0x9E, // #..####.
  0x82, // #.....#.
  0x44, // .#...#..
  0x38, // ..###...
  0x00  // ........
};